spring:  
  config:
    activate:
      on-profile: local
  datasource:
    jdbc-url: jdbc:mariadb://mariadb.neoflow.co.kr:3306/goldstar_schema?characterEncoding=UTF-8
    url: jdbc:mariadb://mariadb.neoflow.co.kr:3306/goldstar_schema?characterEncoding=UTF-8
    driver-class-name: org.mariadb.jdbc.Driver
    username: "goldstar"
    password: "goldstar"
    maximumPoolSize: 2
    connectionInitSql: SELECT 1
    connectionTimeout: 30000
  
system:
  domain: http://localhost

multipart:
  path:
    event: "/Users/issuettl/my-directory/event"
    product: "/Users/issuettl/my-directory/product"
    survey: "/Users/issuettl/my-directory/survey"
  
#server.servlet.context-path: /test

#https://devmember.lge.co.kr/auth/empLogin.do?client_id=lge-main-integration&state=VchcCEzJ2aaLiUic9BEyD7lV3VauJ+9jjg3qDDjD2Zg=&redirect_uri=http://test.lge.co.kr:81/sso/api/emp/callbackLogin

lge:
  sso:
    logingo: "\"https://www.lge.co.kr/sso/member/login\""
    logout: "https://www.lge.co.kr/sso/member/logout"
    login: 
      url: "https://member.lge.co.kr/auth/empLogin.do"
      clientId: "lge-main-integration"
      state: "VchcCEzJ2aaLiUic9BEyD7lV3VauJ+9jjg3qDDjD2Zg="
      redirectUrl: "https://goldstar.lge.co.kr/sso/sign/in/action.do"
    account: 
      login: "https://account.lge.co.kr/login/initView"
      logout: "https://account.lge.co.kr/logout/initView"
      clientId: "lgcom-goldstar-integration"
      clientSecret: "BXDRDo9j-UnKY-Ma2Sc-aJxT-Qg0mYBtMPXlL"
      state: "VchcCEzJ2aaLiUic9BEyD7lV3VauJ+9jjg3qDDjD2Zg="
      loginRedirectUrl: "https://goldstar.lge.co.kr/sso/account/in/action.do"
      logoutRedirectUrl: "https://goldstar.lge.co.kr/u/page/index.do"
      getSession: "https://account.lge.co.kr/api/session/get"
      tokenConfirm: "https://account.lge.co.kr/api/session/check"
      tokenRefresh: "https://account.lge.co.kr/api/session/refresh"
      getMember: "https://account.lge.co.kr/api/member/get"
      oauth2BackendUrl: "https://kr.lgeapi.com/"
  oauth:
    host: "https://kr.lgeapi.com"
    appKey: "6c20d5b71f304c85b84eb1a7282bd4ce"
    secret: "f79d632450d548268d1ed8a7f025aa61"
    uri:
      datetime: "/oauth/1.0/datetime"
      token: "/oauth/1.0/oauth2/token"
      tokenConfirm: "/oauth/1.5/token"
      userProfile: "/oauth/1.0/users/profile"
  url:
    gnb: "https://www.lge.co.kr/gnb"
    footer: "https://www.lge.co.kr/footer"
    domain: "https://www.lge.co.kr/"